/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ggroup.panels;

/**
 *
 * @author 1513 IRON
 */
public class PanelTask extends javax.swing.JPanel {

   /**
    * Creates new form PanelTask
    */
   public PanelTask() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanelOptions = new javax.swing.JPanel();
      jButton1 = new javax.swing.JButton();
      jButtonStart = new javax.swing.JButton();
      jButtonStop = new javax.swing.JButton();
      jButtonSendToJira = new javax.swing.JButton();
      jTextFieldTime = new javax.swing.JTextField();
      jPanelTitle = new javax.swing.JPanel();
      jLabelTask = new javax.swing.JLabel();

      setLayout(new java.awt.BorderLayout());

      jPanelOptions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

      jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ggroup/resources/details.png"))); // NOI18N
      jButton1.setToolTipText("Issue Details");
      jPanelOptions.add(jButton1);

      jButtonStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ggroup/resources/play.png"))); // NOI18N
      jButtonStart.setToolTipText("Start work");
      jPanelOptions.add(jButtonStart);

      jButtonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ggroup/resources/pause.png"))); // NOI18N
      jButtonStop.setToolTipText("Stop work");
      jPanelOptions.add(jButtonStop);

      jButtonSendToJira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ggroup/resources/upload.png"))); // NOI18N
      jButtonSendToJira.setToolTipText("Send to Jira");
      jPanelOptions.add(jButtonSendToJira);

      jTextFieldTime.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      jTextFieldTime.setText("00:00:00");
      jTextFieldTime.setPreferredSize(new java.awt.Dimension(60, 20));
      jPanelOptions.add(jTextFieldTime);

      add(jPanelOptions, java.awt.BorderLayout.LINE_END);

      jPanelTitle.setLayout(new java.awt.BorderLayout());
      jPanelTitle.add(jLabelTask, java.awt.BorderLayout.CENTER);

      add(jPanelTitle, java.awt.BorderLayout.CENTER);
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButtonSendToJira;
   private javax.swing.JButton jButtonStart;
   private javax.swing.JButton jButtonStop;
   private javax.swing.JLabel jLabelTask;
   private javax.swing.JPanel jPanelOptions;
   private javax.swing.JPanel jPanelTitle;
   private javax.swing.JTextField jTextFieldTime;
   // End of variables declaration//GEN-END:variables
}
